babycare/urls.py
from django.urls import path

from . import views

app_name = 'babycare'
urlpatterns = [
    # Define your URL patterns here
    path('fetch/submit_feeding/', views.fetch_submit_feeding,
         name='fetch_submit_feeding'),
    path('fetch/submit_breast_bumping/', views.fetch_submit_breast_bumping,
         name='fetch_submit_breast_bumping'),
    path('fetch/submit_body_temperature/', views.fetch_submit_body_temperature,
         name='fetch_submit_body_temperature'),
    path('fetch/submit_growth_data/', views.fetch_submit_growth_data,
         name='fetch_submit_growth_data'),
    path('fetch/submit_diaper/', views.fetch_submit_diaper,
         name='fetch_submit_diaper'),
    path('fetch/submit_misc_record/', views.fetch_submit_misc_record,
         name='fetch_submit_misc_record'),
    path('fetch/fenton-data/<str:fenton_type>/<int:baby_date_id>/',
        views.fetch_fenton_data, name='fetch_fenton_data'), 

    path('', views.index, name='index'),
    path('create/', views.create_baby_date, name='create_baby_date'),
    path('feedings/<int:baby_date_id>/',
         views.feeding_list, name='feedings_list'),
    path('body_temperatures/<int:baby_date_id>',
         views.BodyTemperatureListView.as_view(),
         name='body_temperatures_list'),
    path('growth_datas/<int:baby_date_id>',
         views.GrowthDataListView.as_view(), name='growth_datas_list'),
    path('diapers/<int:baby_date_id>',
         views.DiaperListView.as_view(), name='diapers_list'),
    path('misc_records/<int:baby_date_id>',
         views.MiscRecordListView.as_view(), name='misc_records_list'),
    path('baby_date_relate_request/', views.baby_date_relate_request,
         name='baby_date_relate_request'),
    path('approve_baby_date_relate_request/',
         views.approve_baby_date_relate_request,
         name='approve_baby_date_relate_request'),
    path(
        'submit_feeding_with_time/',
        views.submit_feeding_with_time,
        name='submit_feeding_with_time',
    ),
]

iuser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('register/', views.user_register, name='register'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', RedirectView.as_view(url='/dashboard/', permanent=False), name='home'),
    path('0725accounts/', include('iuser.urls')),
    path('zh/admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('shopping_list/', include('shopping_list.urls')),
    path('task_calendar/', include('task_calendar.urls')),
    path('babycare/', include('babycare.urls')),
] + debug_toolbar_urls()

babycare/views.py
from typing import Any, Dict
from datetime import timedelta, datetime, time

from django.utils import timezone, dateparse, decorators
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, Http404, HttpResponseForbidden, JsonResponse
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.generic.list import ListView
from django.db.models import Sum
from django.contrib.messages import add_message, constants as messages
from django.utils.html import escape

from babycare import models
from babycare.modelforms import (
    FeedingForm, FeedingWithTimeForm, BreastBumpingForm, BodyTemperatureForm, GrowthDataForm, BabyDateForm, DiaperForm, MiscRecordForm)
from iuser.decorators import login_or_404
from utils.datetime import get_local_date, get_range_of_date


# Create your views here.
@login_or_404
def index(request: HttpRequest) -> HttpResponse:
    context = dict()
    context['active'] = 'babycare'

    guardianings = models.BabyRelation.objects.filter(
        request_by=request.user, 
        status=models.BabyRelation.REQUEST_STATUS[2][0]
    )
    for guardianing in guardianings:
        to_approve = models.BabyRelation.objects.filter(
            baby_date=guardianing.baby_date,
            status=models.BabyRelation.REQUEST_STATUS[0][0]
        )
        if context.get('to_approve') is None:
            context['to_approve'] = to_approve
        else:
            to_approve.union(models.BabyRelation.objects.filter(
                baby_date=guardianing.baby_date,
                status=models.BabyRelation.REQUEST_STATUS[0][0]
            ))

    context['babies'] = babies = []
    relations = models.BabyRelation.objects.filter(
        request_by=request.user,
        status__in=models.BabyRelation.accessible_status(),
    ).select_related('baby_date')
    for relation in relations:
        baby_date = relation.baby_date
        nickname = relation.baby_date.nickname
        feedings = models.Feeding.objects.filter(
            baby_date=baby_date.pk)
        if feedings.exists():
            last_feeding = feedings.latest()
            last_feeding_date = get_local_date(last_feeding.feed_at)
            last_feeding_day_range = get_range_of_date(last_feeding_date)
            last_feedings = models.Feeding.objects.filter(
                feed_at__range=last_feeding_day_range)
            last_feedings_amount = sum(map(lambda x: x.amount, last_feedings))
        else:
            last_feedings_amount = None
            last_feeding_date = None
        body_temperatures = models.BodyTemperature.objects.filter(
            baby_date=baby_date.pk)
        if body_temperatures.exists():
            last_body_temperature = body_temperatures.latest()
            last_body_temperature_date = get_local_date(
                last_body_temperature.measure_at)
        else:
            last_body_temperature = None
            last_body_temperature_date = None        
        babies.append((baby_date, nickname, last_feedings_amount, last_feeding_date, last_body_temperature, last_body_temperature_date, relation))
    return render(request, 'babycare/index.html', context)

@login_or_404
def create_baby_date(request: HttpRequest) -> HttpResponse:
    """
    Render the baby date creation page.
    """
    context = dict()
    context['active'] = 'babycare'
    if request.method == 'GET':
        context['form'] = BabyDateForm()
        return render(request, 'babycare/baby_date_create.html', context)
    elif request.method == 'POST':
        form = BabyDateForm(request.POST)
        if form.is_valid():
            babydate = form.save()
            models.BabyRelation.objects.create(
                baby_date=babydate,
                request_by=request.user,
                approve_by=request.user,
                approve_at=timezone.now(),
                status=models.BabyRelation.REQUEST_STATUS[2][0],
            )
            return redirect('dashboard:index')
        else:
            print(form.errors)
    raise Http404()


@login_or_404
def baby_date_relate_request(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(request, 'babycare/baby_date_relate_request.html')
    elif request.method == 'POST':
        nickname = request.POST.get('nickname')
        nickname = "" if nickname is None else nickname.strip()
        if nickname:
            baby_date = models.BabyDate.objects.filter(nickname=nickname).first()
            if baby_date is not None:
                _, created = models.BabyRelation.objects.get_or_create(
                    baby_date=baby_date, 
                    request_by=request.user,
                    )
                if created:
                    add_message(
                        request, 
                        messages.SUCCESS, 
                        f'已申请关联 {nickname}'
                    )
                else:
                    add_message(
                        request, 
                        messages.WARNING, 
                        f'已申请过关联 {nickname}'
                    )
                return redirect('babycare:index')
        nickname = escape(nickname)
        add_message(request, messages.ERROR, f'没有找到名为{nickname}的宝宝')
        return redirect('babycare:index')
    else:
        return HttpResponseBadRequest()


@require_POST
def approve_baby_date_relate_request(request: HttpRequest) -> HttpResponse:
    status = request.POST.get('status', "")
    if status.isdigit():
        status = int(status)
        if status not in models.BabyRelation.granted_status():
            # 是数字且不在授权后的状态视为恶意请求
            return HttpResponseBadRequest()
        print(request.POST)
        baby_relation_id = request.POST.get('baby_relation_id', "")
        if baby_relation_id.isdigit():
            baby_relation_id = int(baby_relation_id)
        else:
            return HttpResponseBadRequest()
        relation = models.BabyRelation.objects.filter(
            id=baby_relation_id,
            status__in=models.BabyRelation.pending_status(),
        ).first()
        if relation is not None:
            if relation.can_be_approved_by(request.user):
                if status in models.BabyRelation.reject_status():
                    relation.delete()
                else:
                    relation.status = status
                    relation.approve_by = request.user
                    relation.approve_at = timezone.now()
                    relation.save()
                add_message(
                    request, 
                    messages.SUCCESS, 
                    f'已处理{relation.request_by.username}和{relation.baby_date.nickname}关联'
                )
                return redirect('babycare:index')
            else:
                """该用户无权处理"""
                return HttpResponseForbidden()
        else:
            """该关联不存在或状态已经不是待处理"""
            add_message(
                request,
                messages.WARNING,
                '该关联请求已经由别人处理'
            )
            return redirect('babycare:index')
    else:
        # 状态不正确 可能是默认的空选项
        add_message(
            request,
            messages.WARNING,
            '请选择正确的处理方式'
        )
        return redirect('babycare:index')


@require_POST
def fetch_submit_feeding(request: HttpRequest) -> HttpResponse:
    """
    Handle the submission of feeding data via AJAX.
    """
    form = FeedingForm(request.POST)
    if form.is_valid():
        feeding = form.save(commit=False)
        relation = models.BabyRelation.objects.filter(
            baby_date=feeding.baby_date,
            request_by=request.user,
            status__in=models.BabyRelation.editable_status(),
        ).exists()
        if relation:
            feeding.save()
        else:
            return HttpResponseForbidden()
    else:
        print(form.errors)
    url = reverse('dashboard:index')
    url += f'?babycare_active=baby-feeding'
    return HttpResponseRedirect(url)


@require_POST
def fetch_submit_breast_bumping(request: HttpRequest) -> HttpResponse:
    """
    Handle the submission of breast bumping data via AJAX.
    """
    form = BreastBumpingForm(request.POST)
    if form.is_valid():
        breast_bumping = form.save(commit=False)
        relation = models.BabyRelation.objects.filter(
            baby_date=breast_bumping.baby_date,
            request_by=request.user,
            status__in=models.BabyRelation.editable_status(),
        ).exists()
        if relation:
            breast_bumping.save()
        else:
            return HttpResponseForbidden()
    else:
        print(form.errors)
    url = reverse('dashboard:index')
    url += f'?babycare_active=breast-bumping'
    return HttpResponseRedirect(url)


@require_POST
def fetch_submit_body_temperature(request: HttpRequest) -> HttpResponse:
    """
    Handle the submission of body temperature data via AJAX.
    """
    form = BodyTemperatureForm(request.POST)
    if form.is_valid():
        body_temperature = form.save(commit=False)
        relation = models.BabyRelation.objects.filter(
            baby_date=body_temperature.baby_date,
            request_by=request.user,
            status__in=models.BabyRelation.editable_status(),
        ).exists()
        if relation:
            body_temperature.save()
        else:
            return HttpResponseForbidden()
    else:
        print(form.errors)
    url = reverse('dashboard:index')
    url += f'?babycare_active=body-temperature'
    return HttpResponseRedirect(url)


@require_POST
def fetch_submit_growth_data(request: HttpRequest) -> HttpResponse:
    """
    Handle the submission of growth data via AJAX.
    """
    form = GrowthDataForm(request.POST)
    if form.is_valid():
        growth_data = form.save(commit=False)
        relation = models.BabyRelation.objects.filter(
            baby_date=growth_data.baby_date,

babycare/templates/babycare/includes/baby_create_or_link.html
<div id="baby-date-request-buttons">
    <a class="btn btn-primary m-1" href="{% url 'babycare:create_baby_date' %}"><i class="bi bi-person-add"></i> 创建宝宝信息</a>
    <a class="btn btn-info m-1" href="{% url 'babycare:baby_date_relate_request' %}"><i class="bi bi-link"></i> 关联现有宝宝</a>
</div>

babycare/templates/babycare/includes/baby_record.html
{% load babycare_tags %}

<div id="baby-record-wrapper" class="switcher" data-switcher-name="babycare">
    <div class="switcher-buttons d-inline-flex" id="baby-record-buttons">
        <span class="switcher-button{% if babycare_active == 'baby-feeding' %} active-button{% endif %}" data-target="baby-feeding">喂奶量</span>
        <span class="switcher-button{% if babycare_active == 'body-temperature' %} active-button{% endif %}" data-target="body-temperature">体温</span>
        <span class="switcher-button{% if babycare_active == 'growth-data' %} active-button{% endif %}" data-target="growth-data">生长数据</span>
        <span class="switcher-button{% if babycare_active == 'diaper' %} active-button{% endif %}" data-target="diaper">尿布</span>
        <span class="switcher-button{% if babycare_active == 'misc-record' %} active-button{% endif %}" data-target="misc-record">其他</span>
    </div>
    <div class="switcher-contents" id="baby-record-contents">
        <div class="switcher-content{% if babycare_active == 'baby-feeding' %} active-content{% endif %} container" id="baby-feeding">
            <div>
                <form action="{% url 'babycare:fetch_submit_feeding' %}" method="post">
                {{ feeding_form.as_p }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-sm">提交</button> 
                </form>
            </div>
            {% if feedings %}
            <div class="my-1 p-1">距离上次喂奶过去了 {{ feedings.0.feed_at|zh_timesince }}</div>
            {% endif %}
            <div>
                {% include 'babycare/includes/feedings_list_table.html' %}
            </div>
            <div class="p-1"><a href="{% url 'babycare:feedings_list' baby_date_id=baby_date.id %}">查看所有</a></div>
        </div>
        <div class="switcher-content{% if babycare_active == 'body-temperature' %} active-content{% endif %} container" id="body-temperature">
            <div>
                <form action="{% url 'babycare:fetch_submit_body_temperature' %}" method="post">
                {{ body_temperature_form.as_p }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-sm">提交</button> 
                </form>
            </div>
            <div>
                {% include 'babycare/includes/body_temperatures_list_table.html' %}
            </div>
            <div class="p-1"><a href="{% url 'babycare:body_temperatures_list' baby_date_id=baby_date.id %}">查看所有</a></div>
        </div>
        <div class="switcher-content{% if babycare_active == 'growth-data' %} active-content{% endif %} container" id="growth-data">
            <div>
                <form action="{% url 'babycare:fetch_submit_growth_data' %}" method="post">
                    {{ growth_data_form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-sm">提交</button> 
                </form>
            </div>
            <div>
                {% include 'babycare/includes/growth_datas_list_table.html' %}
            </div>
            <div class="p-1"><a href="{% url 'babycare:growth_datas_list' baby_date_id=baby_date.id %}">查看所有</a></div>
        </div>
        <div class="switcher-content{% if babycare_active == 'diaper' %} active-content{% endif %} container" id="diaper">
            <div>
                <form action="{% url 'babycare:fetch_submit_diaper' %}" method="post">
                    {{ diaper_form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-sm">提交</button> 
                </form>
            </div>
            <div>
                {% include 'babycare/includes/diapers_list_table.html' %}
            </div>
            <div class="p-1"><a href="{% url 'babycare:diapers_list' baby_date_id=baby_date.id %}">查看所有</a></div>
        </div>
        <div class="switcher-content{% if babycare_active == 'misc-record' %} active-content{% endif %} container" id="misc-record">
            <div>
                <form action="{% url 'babycare:fetch_submit_misc_record' %}" method="post">
                {{ misc_record_form.as_p }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-sm">提交</button> 
                </form>
            </div>
            <div>
                {% include 'babycare/includes/misc_records_list_table.html' %}
            </div>
            <div class="p-1"><a href="{% url 'babycare:misc_records_list' baby_date_id=baby_date.id %}">查看所有</a></div>
        </div>
    </div>
</div>

babycare/templates/babycare/includes/babydate.html
{% load babycare_tags %}
<div id="baby-date">
{% if baby_date.is_born %}
    {% if baby_date.is_preterm %}
        {% if baby_date.days_to_due < 0 %}
            {# 早产儿足月 显示矫正月龄、PMA以及实际月龄 #}
            <div id="baby-date-wrapper" class="switcher">
                <div class="switcher-buttons d-inline-flex" id="baby-age-buttons">
                    <span class="switcher-button active-button" data-target="baby-age-chron">实际月龄</span>
                    <span class="switcher-button" data-target="baby-age-corrected">矫正月龄</span>
                    <span class="switcher-button" data-target="baby-age-pma">PMA</span>
                </div>
                <div class="switcher-contents" id="baby-age">
                    <div class="switcher-content active-content" id="baby-age-chron">宝宝实际月龄是{{ baby_date.get_chronological_age_days|get_age_months }}</div>
                    <div class="switcher-content" id="baby-age-corrected">宝宝矫正月龄是{{ baby_date.get_corrected_age_days|get_age_months }}</div>
                    <div class="switcher-content" id="baby-age-pma">宝宝妊娠起点总周龄是{{ baby_date|get_gestational_age_weeks:False }}</div>
                </div>
            </div>
            {% else %}
            {# 早产儿未足月 显示实际月龄和PMA #}
            <div id="baby-date-wrapper" class="switcher">
                <div class="switcher-buttons d-inline-flex" id="baby-age-buttons">
                    <span class="switcher-button active-button" data-target="baby-age-chron">实际月龄</span>
                    <span class="switcher-button" data-target="baby-age-pma">PMA</span>
                </div>
                <div class="switcher-contents" id="baby-age">
                    <div class="switcher-content active-content" id="baby-age-chron">宝宝实际月龄是{{ baby_date.get_chronological_age_days|get_age_months }}</div>
                    <div class="switcher-content" id="baby-age-pma">宝宝妊娠总周龄是{{ baby_date|get_gestational_age_weeks:False }}</div>
                </div>
            </div>
        {% endif %}
    {% else %}
        {# 正常足月的婴儿 仅显示实际月龄 #}
        <div id="baby-date-wrapper">宝宝现在是{{ baby_date.get_chronological_age_days|get_age_months }}</div>
    {% endif %}
{% else %}
    <div id="baby-date-wrapper" class="switcher">
        <div class="switcher-buttons d-inline-flex" id="baby-ga-buttons">
            <span class="switcher-button active-button" data-target="baby-ga-lmp">LMP估算</span>
            <span class="switcher-button" data-target="baby-ga-us">超声估算</span>
        </div>
        <div class="switcher-contents" id="baby-ga">
            <div class="switcher-content active-content" id="baby-ga-lmp">宝宝现在是{{ baby_date|get_gestational_age_weeks:False }}</div>
            <div class="switcher-content" id="baby-ga-us">宝宝现在是{{ baby_date|get_gestational_age_weeks:True }}</div>
        </div>
    </div>
    {% with baby_date.days_to_due as dtd %}
        <div>距离预产期{{baby_date.estimated_due_date|date:"Y年m月d日"}}{% if dtd >= 0%}还有{{ baby_date.days_to_due }}{% else %}已经过了{{ baby_date.days_to_due|cut:"-" }}{% endif %}天</div>
    {% endwith %}
{% endif %}
</div>

babycare/templates/babycare/includes/body_temperatures_list_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>测量时间</th>
            <th>体温 (°C)</th>
            <th>方式</th>
        </tr>
    </thead>
    <tbody>
    {% for body_temp in body_temperatures %}
        <tr>
            <td>{{ body_temp.measure_at|date:"Y-m-d H:i" }}</td>
            <td>{{ body_temp.temperature }}{% if body_temp.notes %}<i class="bi bi-info-circle" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ body_temp.notes }}"></i>{% endif %}</td>
            <td>{{ body_temp.get_measurement_display }}</td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="4">暂无体温记录</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

babycare/templates/babycare/includes/diapers_list_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>时间</th>
            <th>大便</th>
            <th>小便</th>
        </tr>
    </thead>
    <tbody>
    {% for diaper in diapers %}
        <tr>
            <td>{{ diaper.create_at|date:"Y-m-d H:i" }}{% if diaper.notes %}<i class="bi bi-info-circle" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ diaper.notes }}"></i>{% endif %}</td>
            <td {% if diaper.get_pooh_desc %}style="background-color: {{ diaper.get_pooh_style }};text-decoration: underline dotted;" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ diaper.get_pooh_desc }}"{% endif %}>{{ diaper.get_pooh_amount_display }}</td>
            <td {% if diaper.pee_amount != "0" %}style="background-color: {{ diaper.get_pee_style }};text-decoration: underline dotted;" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ diaper.get_pee_color_display }}"{% endif %}>{{ diaper.get_pee_amount_display }}</td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="4">暂无尿布记录</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

babycare/templates/babycare/includes/feedings_list_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>喂奶时间</th>
            <th>喂奶量</th>
        </tr>
    </thead>
    <tbody>
    {% for feeding in feedings %}
        <tr>
            <td>{{ feeding.feed_at|date:"Y-m-d H:i" }}</td>
            <td>{{ feeding.amount }} ml {% if feeding.note %}<i class="bi bi-info-circle" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ feeding.note }}"></i>{% endif %}</td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="3">暂无喂奶记录</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

babycare/templates/babycare/includes/growth_datas_list_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>记录时间</th>
            <th>体重 (kg)</th>
            <th>身高 (cm)</th>
            <th>头围 (cm)</th>
        </tr>
    </thead>
    <tbody>
        {% for growth in growth_data %}
            <tr>
                <td>{{ growth.record_at|date:"Y-m-d" }}{% if growth.notes %}<i class="bi bi-info-circle" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ growth.notes }}"></i>{% endif %}</td>
                <td>{{ growth.weight|default:"-" }}</td>
                <td>{{ growth.height|default:"-" }}</td>
                <td>{{ growth.head_circumference|default:"-" }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">暂无生长数据记录</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

babycare/templates/babycare/includes/misc_records_list_table.html
<table class="table table-striped">
    <thead>
        <tr>
            <th>使用时间</th>
            <th>用品名</th>
        </tr>
    </thead>
    <tbody>
    {% for misc_record in misc_records %}
        <tr>
            <td>{{ misc_record.record_at|date:"Y-m-d H:i" }}</td>
            <td>{{ misc_record.misc_item.item_name }} {% if feeding.note %}<i class="bi bi-info-circle" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ feeding.note }}"></i>{% endif %}</td>
        </tr>
    {% empty %}
        <tr>
            <td colspan="3">暂无用品记录</td>
        </tr>
    {% endfor %}
    </tbody>
</table>