babycare/urls.py
from django.urls import path

from . import views

app_name = 'babycare'
urlpatterns = [
    # Define your URL patterns here
    path('fetch/submit_feeding/', views.fetch_submit_feeding,
         name='fetch_submit_feeding'),
    path('fetch/submit_breast_bumping/', views.fetch_submit_breast_bumping,
         name='fetch_submit_breast_bumping'),
    path('fetch/submit_body_temperature/', views.fetch_submit_body_temperature,
         name='fetch_submit_body_temperature'),
    path('fetch/submit_growth_data/', views.fetch_submit_growth_data,
         name='fetch_submit_growth_data'),
    path('fetch/submit_diaper/', views.fetch_submit_diaper,
         name='fetch_submit_diaper'),
    path('fetch/submit_misc_record/', views.fetch_submit_misc_record,
         name='fetch_submit_misc_record'),
    path('fetch/fenton-data/<str:fenton_type>/<int:baby_date_id>/',
        views.fetch_fenton_data, name='fetch_fenton_data'), 

    path('', views.index, name='index'),
    path('create/', views.create_baby_date, name='create_baby_date'),
    path('feedings/<int:baby_date_id>/',
         views.feeding_list, name='feedings_list'),
    path('body_temperatures/<int:baby_date_id>',
         views.BodyTemperatureListView.as_view(),
         name='body_temperatures_list'),
    path('growth_datas/<int:baby_date_id>',
         views.GrowthDataListView.as_view(), name='growth_datas_list'),
    path('diapers/<int:baby_date_id>',
         views.DiaperListView.as_view(), name='diapers_list'),
    path('misc_records/<int:baby_date_id>',
         views.MiscRecordListView.as_view(), name='misc_records_list'),
    path('baby_date_relate_request/', views.baby_date_relate_request,
         name='baby_date_relate_request'),
    path('approve_baby_date_relate_request/',
         views.approve_baby_date_relate_request,
         name='approve_baby_date_relate_request'),
    path(
        'submit_feeding_with_time/',
        views.submit_feeding_with_time,
        name='submit_feeding_with_time',
    ),
]

iuser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('register/', views.user_register, name='register'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', RedirectView.as_view(url='/dashboard/', permanent=False), name='home'),
    path('0725accounts/', include('iuser.urls')),
    path('zh/admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('shopping_list/', include('shopping_list.urls')),
    path('task_calendar/', include('task_calendar.urls')),
    path('babycare/', include('babycare.urls')),
] + debug_toolbar_urls()

babycare/views.py
from typing import Any, Dict
from datetime import timedelta, datetime, time

from django.utils import timezone, dateparse, decorators
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, HttpResponseRedirect, Http404, HttpResponseForbidden, JsonResponse
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.generic.list import ListView
from django.db.models import Sum
from django.contrib.messages import add_message, constants as messages
from django.utils.html import escape

from babycare import models
from babycare.modelforms import (
    FeedingForm, FeedingWithTimeForm, BreastBumpingForm, BodyTemperatureForm, GrowthDataForm, BabyDateForm, DiaperForm, MiscRecordForm)
from iuser.decorators import login_or_404
from utils.datetime import get_local_date, get_range_of_date


# Create your views here.
@login_or_404
def index(request: HttpRequest) -> HttpResponse:
    context = dict()
    context['active'] = 'babycare'

    guardianings = models.BabyRelation.objects.filter(
        request_by=request.user, 
        status=models.BabyRelation.REQUEST_STATUS[2][0]
    )
    for guardianing in guardianings:
        to_approve = models.BabyRelation.objects.filter(
            baby_date=guardianing.baby_date,
            status=models.BabyRelation.REQUEST_STATUS[0][0]
        )
        if context.get('to_approve') is None:
            context['to_approve'] = to_approve
        else:
            to_approve.union(models.BabyRelation.objects.filter(
                baby_date=guardianing.baby_date,
                status=models.BabyRelation.REQUEST_STATUS[0][0]
            ))

    context['babies'] = babies = []
    relations = models.BabyRelation.objects.filter(
        request_by=request.user,
        status__in=models.BabyRelation.accessible_status(),
    ).select_related('baby_date')
    for relation in relations:
        baby_date = relation.baby_date
        nickname = relation.baby_date.nickname
        feedings = models.Feeding.objects.filter(
            baby_date=baby_date.pk)
        if feedings.exists():
            last_feeding = feedings.latest()
            last_feeding_date = get_local_date(last_feeding.feed_at)
            last_feeding_day_range = get_range_of_date(last_feeding_date)
            last_feedings = models.Feeding.objects.filter(
                feed_at__range=last_feeding_day_range)
            last_feedings_amount = sum(map(lambda x: x.amount, last_feedings))
        else:
            last_feedings_amount = None
            last_feeding_date = None
        body_temperatures = models.BodyTemperature.objects.filter(
            baby_date=baby_date.pk)
        if body_temperatures.exists():
            last_body_temperature = body_temperatures.latest()
            last_body_temperature_date = get_local_date(
                last_body_temperature.measure_at)
        else:
            last_body_temperature = None
            last_body_temperature_date = None        
        babies.append((baby_date, nickname, last_feedings_amount, last_feeding_date, last_body_temperature, last_body_temperature_date, relation))
    return render(request, 'babycare/index.html', context)

@login_or_404
def create_baby_date(request: HttpRequest) -> HttpResponse:
    """
    Render the baby date creation page.
    """
    context = dict()
    context['active'] = 'babycare'
    if request.method == 'GET':
        context['form'] = BabyDateForm()
        return render(request, 'babycare/baby_date_create.html', context)
    elif request.method == 'POST':
        form = BabyDateForm(request.POST)
        if form.is_valid():
            babydate = form.save()
            models.BabyRelation.objects.create(
                baby_date=babydate,
                request_by=request.user,
                approve_by=request.user,
                approve_at=timezone.now(),
                status=models.BabyRelation.REQUEST_STATUS[2][0],
            )
            return redirect('dashboard:index')
        else:
            print(form.errors)
    raise Http404()


@login_or_404
def baby_date_relate_request(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(request, 'babycare/baby_date_relate_request.html')
    elif request.method == 'POST':
        nickname = request.POST.get('nickname')
        nickname = "" if nickname is None else nickname.strip()
        if nickname:
            baby_date = models.BabyDate.objects.filter(nickname=nickname).first()
            if baby_date is not None:
                _, created = models.BabyRelation.objects.get_or_create(
                    baby_date=baby_date, 
                    request_by=request.user,
                    )
                if created:
                    add_message(
                        request, 
                        messages.SUCCESS, 
                        f'已申请关联 {nickname}'
                    )
                else:
                    add_message(
                        request, 
                        messages.WARNING, 
                        f'已申请过关联 {nickname}'
                    )
                return redirect('babycare:index')
        nickname = escape(nickname)
        add_message(request, messages.ERROR, f'没有找到名为{nickname}的宝宝')
        return redirect('babycare:index')
    else:
        return HttpResponseBadRequest()


@require_POST
def approve_baby_date_relate_request(request: HttpRequest) -> HttpResponse:
    status = request.POST.get('status', "")
    if status.isdigit():
        status = int(status)
        if status not in models.BabyRelation.granted_status():
            # 是数字且不在授权后的状态视为恶意请求
            return HttpResponseBadRequest()
        print(request.POST)
        baby_relation_id = request.POST.get('baby_relation_id', "")
        if baby_relation_id.isdigit():
            baby_relation_id = int(baby_relation_id)
        else:
            return HttpResponseBadRequest()
        relation = models.BabyRelation.objects.filter(
            id=baby_relation_id,
            status__in=models.BabyRelation.pending_status(),
        ).first()
        if relation is not None:
            if relation.can_be_approved_by(request.user):
                if status in models.BabyRelation.reject_status():
                    relation.delete()
                else:
                    relation.status = status
                    relation.approve_by = request.user
                    relation.approve_at = timezone.now()
                    relation.save()
                add_message(
                    request, 
                    messages.SUCCESS, 
                    f'已处理{relation.request_by.username}和{relation.baby_date.nickname}关联'
                )
                return redirect('babycare:index')
            else:
                """该用户无权处理"""
                return HttpResponseForbidden()
        else:
            """该关联不存在或状态已经不是待处理"""
            add_message(
                request,
                messages.WARNING,
                '该关联请求已经由别人处理'
            )
            return redirect('babycare:index')
    else:
        # 状态不正确 可能是默认的空选项
        add_message(
            request,
            messages.WARNING,
            '请选择正确的处理方式'
        )
        return redirect('babycare:index')


@require_POST
def fetch_submit_feeding(request: HttpRequest) -> HttpResponse:
    """
    Handle the submission of feeding data via AJAX.
    """
    form = FeedingForm(request.POST)
    if form.is_valid():
        feeding = form.save(commit=False)
        relation = models.BabyRelation.objects.filter(
            baby_date=feeding.baby_date,
            request_by=request.user,
            status__in=models.BabyRelation.editable_status(),
        ).exists()
        if relation:
            feeding.save()
        else:
            return HttpResponseForbidden()
    else:
        print(form.errors)
    url = reverse('dashboard:index')
    url += f'?babycare_active=baby-feeding'
    return HttpResponseRedirect(url)


@require_POST
def fetch_submit_breast_bumping(request: HttpRequest) -> HttpResponse:
    """
    Handle the submission of breast bumping data via AJAX.
    """
    form = BreastBumpingForm(request.POST)
    if form.is_valid():
        breast_bumping = form.save(commit=False)
        relation = models.BabyRelation.objects.filter(
            baby_date=breast_bumping.baby_date,
            request_by=request.user,
            status__in=models.BabyRelation.editable_status(),
        ).exists()
        if relation:
            breast_bumping.save()
        else:
            return HttpResponseForbidden()
    else:
        print(form.errors)
    url = reverse('dashboard:index')
    url += f'?babycare_active=breast-bumping'
    return HttpResponseRedirect(url)


@require_POST
def fetch_submit_body_temperature(request: HttpRequest) -> HttpResponse:
    """
    Handle the submission of body temperature data via AJAX.
    """
    form = BodyTemperatureForm(request.POST)
    if form.is_valid():
        body_temperature = form.save(commit=False)
        relation = models.BabyRelation.objects.filter(
            baby_date=body_temperature.baby_date,
            request_by=request.user,
            status__in=models.BabyRelation.editable_status(),
        ).exists()
        if relation:
            body_temperature.save()
        else:
            return HttpResponseForbidden()
    else:
        print(form.errors)
    url = reverse('dashboard:index')
    url += f'?babycare_active=body-temperature'
    return HttpResponseRedirect(url)


@require_POST
def fetch_submit_growth_data(request: HttpRequest) -> HttpResponse:
    """
    Handle the submission of growth data via AJAX.
    """
    form = GrowthDataForm(request.POST)
    if form.is_valid():
        growth_data = form.save(commit=False)
        relation = models.BabyRelation.objects.filter(
            baby_date=growth_data.baby_date,

babycare/templates/babycare/baby_date_create.html
{% extends "dashboard/base.html" %}

{% block title %}创建宝宝信息{% endblock %}

{% block main %}
<form action="" method="POST">
    {{form.as_p}}
    {% csrf_token %}
    <button class="btn btn-primary">创建宝宝信息</button>
</form>
{% endblock %}

{% block aside %}
{% endblock %}

babycare/templates/babycare/baby_date_relate_request.html
{% extends "dashboard/base.html" %}

{% block title %}关联宝宝{% endblock %}

{% block main %}
<form class="form-control" action="" method="POST">
    <label for="baby-nickname">关心的宝宝昵称:</label>
    <input type="text" name="nickname" id="baby-nickname">
    {% csrf_token %}
    <button class="btn btn-primary">关联宝宝</button>
</form>
{% endblock %}

{% block aside %}
{% endblock %}

babycare/templates/babycare/body_temperatures_list.html
{% extends 'dashboard/base.html' %}

{% block main %}
<section>
    <h2>体温</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>测量时间</th>
                <th>体温 (°C)</th>
                <th>测量方式</th>
                <th>备注</th>
            </tr>
        </thead>
        <tbody>
        {% for body_temp in body_temperatures %}
            <tr>
                <td>{{ body_temp.date|date:"Y年m月d日 H:i" }}</td>
                <td>{{ body_temp.temperature }}</td>
                <td>{{ body_temp.get_measurement_display }}</td>
                <td>{{ body_temp.notes }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4">暂无体温记录</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include 'dashboard/includes/pagination.html' %}
</section>
{% endblock %}

{% block aside %}
{% endblock %}

babycare/templates/babycare/diapers_list.html
{% extends 'dashboard/base.html' %}

{% block main %}
<section>
    <h2>尿布</h2>
    {% include 'babycare/includes/diapers_list_table.html' %}
    {% include 'dashboard/includes/pagination.html' %}
</section>
{% endblock %}

{% block aside %}
{% endblock %}

babycare/templates/babycare/feedings_list.html
{% extends 'dashboard/base.html' %}

{% block title %}成长记录{% endblock %}

{% block main %}
<section>
    <h2>喂奶量</h2>
    {% include 'babycare/includes/feedings_list_table.html' %}
    <form class="my-3" action="{% url 'babycare:submit_feeding_with_time' %}" method="POST">
        <div class="input-group input-group-sm">
            {% for field in feeding_form %}
                {% if not field.is_hidden %}
                    <span class="input-group-text">{{ field.label }}</span>
                    {{ field }}
                {% else %}
                    {{ field}}
                {% endif %}
            {% endfor %}
            {% csrf_token %}
            <button class="btn btn-outline-primary" type="submit">提交</button>
        </div>
    </form>
    {% if feedings_total %}
    <div class="p-1 my-2">当日喂奶总量 {{ feedings_total.amount__sum }} ml</div>
    {% endif %}
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link" href="?date={{ previous_day|date:'Y-m-d' }}">{{ previous_day|date:'m-d' }}</a>
        </li>
        <li class="page-item active">
            <form target="_self" method="get" class="auto-submit"><input type="date" name="date" value="{{ feed_date|date:'Y-m-d' }}"></form>
        </li>
        {% if next_day %}
        <li class="page-item">
            <a class="page-link" href="?date={{ next_day|date:'Y-m-d' }}">{{ next_day|date:'m-d' }}</a>
        </li>
        {% endif %}
    </ul>
</section>
{% endblock %}

{% block aside %}
{% endblock %}

babycare/templates/babycare/growth_datas_list.html
{% extends 'dashboard/base.html' %}

{% block main %}
<section>
    <h2>成长数据</h2>
    {% include 'babycare/includes/growth_datas_list_table.html' %}
    {% include 'dashboard/includes/pagination.html' %}
</section>
{% endblock %}

{% block aside %}
{% endblock %}

babycare/templates/babycare/index.html
{% extends "dashboard/base.html" %}
{% load static %}

{% block title %}主页{% endblock %}

{% block main %}
<div class="mb-3">
    {% include 'babycare/includes/baby_create_or_link.html' %}
</div>
{% if to_approve %}
<div class="m-3 p-3">
    {% for relation in to_approve %}
    <div>
        <div class="input-group">
            <form class="form-control" action="{% url 'babycare:approve_baby_date_relate_request' %}" method="post">
                <legend class="fs-6">
                    {{ relation.request_by.username }} 申请关联 {{ relation.baby_date.nickname }}
                </legend>
                <select name="status" class="form-select" id="inputGroupSelect04">
                    <option selected>选择处理方式...</option>
                    <optgroup label="关联为">
                        <option value="2">监护人</option>
                        <option value="3">亲人</option>
                        <option value="4">关心的人</option>
                    </optgroup>
                    <optgroup label="或">
                        <option value="1">拒绝</option>
                    </optgroup>
                </select>
                <input type="hidden" name="baby_relation_id" value="{{ relation.id }}">
                {% csrf_token %}
                <button class="my-1 btn btn-outline-secondary" type="submit">提交</button>
            </form>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% for baby_date, nickname, last_feedings_amount, last_feeding_date, last_body_temperature, last_body_temperature_date, relation in babies %}
<div>
    <h2>{{ nickname }}<i class="bi bi-{{ relation.status_css_class }}"></i></h2>
    <section class="row font-monospace my-3">
        <a class="col-lg-4 col-sm-6 col-8 m-lg-3 mb-sm-3 my-3 mx-auto link-info link-offset-2 link-underline link-underline-opacity-25" href="{% url 'babycare:feedings_list' baby_date_id=baby_date.pk %}">
        <div class="rounded-4 bg-info text-info-emphasis h3 border border-3 border-primary-subtle shadow p-4">
            {% if last_feedings_amount %}
            <div class="text-start fs-6">上一次全天喂奶量:</div>
            <div class="text-start fs-2 fw-bold py-3"><i class="bi bi-droplet"></i>{{ last_feedings_amount|floatformat:"0" }}mL</div>
            <div class="text-end fs-6">{{ last_feeding_date|date:"Y-m-d" }}</div>
            {% else %}
            <div class="text-start fs-6">没有喂奶记录</div>
            {% endif %}
        </div>
        </a>
        <a class="col-lg-4 col-sm-6 col-8 m-lg-3 mb-sm-3 my-3 mx-auto link-info link-offset-2 link-underline link-underline-opacity-25" href="{% url 'babycare:body_temperatures_list' baby_date_id=baby_date.pk %}">
        <div class="rounded-4 bg-info text-info-emphasis h3 border border-3 border-primary-subtle shadow p-4">
            {% if last_body_temperature %}
            <div class="text-start fs-6">上一次体温:</div>
            <div class="text-start fs-2 fw-bold py-3"><i class="bi bi-thermometer-half"></i>{{ last_body_temperature.temperature|floatformat:"1" }}°C</div>
            <div class="text-end fs-6">{{ last_body_temperature_date|date:"Y-m-d" }}</div>
            {% else %}
            <div class="text-start fs-6">没有体温记录</div>
            {% endif %}
        </div>
        </a>
    </section>
    <section class="px-0 row text-center">
        <div class="text-center fw-bolder my-2">体重曲线</div>
        <div class="fenton-curve col-12" data-fenton-type="weight" data-start-date="{{ baby_date.last_menstrual_period|date:'Y-m-d' }}" data-fenton-curve-url="{% if baby_date.gender == 'M' %}{% static 'json/babycare/boys_weight.json' %}{% elif baby_date.gender == 'F' %}{% static 'json/babycare/girls_weight.json' %}{% endif %}" data-curve-data-url="{% url 'babycare:fetch_fenton_data' fenton_type='weight' baby_date_id=baby_date.pk %}"></div>
    </section>
    <section class="px-0 row text-center">
        <div class="text-center fw-bolder my-2">身高曲线</div>
        <div class="fenton-curve col-12" data-fenton-type="height" data-start-date="{{ baby_date.last_menstrual_period|date:'Y-m-d' }}" data-fenton-curve-url="{% if baby_date.gender == 'M' %}{% static 'json/babycare/boys_length.json' %}{% elif baby_date.gender == 'F' %}{% static 'json/babycare/girls_length.json' %}{% endif %}" data-curve-data-url="{% url 'babycare:fetch_fenton_data' fenton_type='height' baby_date_id=baby_date.pk %}"></div>
    </section>
    <section class="px-0 row text-center">
        <div class="text-center fw-bolder my-2">头围曲线</div>
        <div class="fenton-curve col-12" data-fenton-type="head_circumference" data-start-date="{{ baby_date.last_menstrual_period|date:'Y-m-d' }}" data-fenton-curve-url="{% if baby_date.gender == 'M' %}{% static 'json/babycare/boys_head_circumference.json' %}{% elif baby_date.gender == 'F' %}{% static 'json/babycare/girls_head_circumference.json' %}{% endif %}" data-curve-data-url="{% url 'babycare:fetch_fenton_data' fenton_type='head_circumference' baby_date_id=baby_date.pk %}"></div>
    </section>
</div>
<hr>
{% endfor %}
{% endblock %}

{% block aside %}
{% endblock %}

babycare/templates/babycare/misc_records_list.html
{% extends 'dashboard/base.html' %}

{% block main %}
<section>
    <h2>其他用品</h2>
    {% include 'babycare/includes/misc_records_list_table.html' %}
    {% include 'dashboard/includes/pagination.html' %}
</section>
{% endblock %}

{% block aside %}
{% endblock %}