babycare/urls.py
from django.urls import path

from . import views

app_name = 'babycare'
urlpatterns = [
    # Define your URL patterns here
    path('fetch/submit_feeding/', views.fetch_submit_feeding,
         name='fetch_submit_feeding'),
    path('fetch/submit_breast_bumping/', views.fetch_submit_breast_bumping,
         name='fetch_submit_breast_bumping'),
    path('fetch/submit_body_temperature/', views.fetch_submit_body_temperature,
         name='fetch_submit_body_temperature'),
    path('fetch/submit_growth_data/', views.fetch_submit_growth_data,
         name='fetch_submit_growth_data'),
    path('fetch/submit_diaper/', views.fetch_submit_diaper,
         name='fetch_submit_diaper'),
    path('fetch/submit_misc_record/', views.fetch_submit_misc_record,
         name='fetch_submit_misc_record'),
    path('fetch/fenton-data/<str:fenton_type>/<int:baby_date_id>/',
        views.fetch_fenton_data, name='fetch_fenton_data'), 

    path('', views.index, name='index'),
    path('create/', views.create_baby_date, name='create_baby_date'),
    path('feedings/<int:baby_date_id>/',
         views.feeding_list, name='feedings_list'),
    path('body_temperatures/<int:baby_date_id>',
         views.BodyTemperatureListView.as_view(),
         name='body_temperatures_list'),
    path('growth_datas/<int:baby_date_id>',
         views.GrowthDataListView.as_view(), name='growth_datas_list'),
    path('diapers/<int:baby_date_id>',
         views.DiaperListView.as_view(), name='diapers_list'),
    path('misc_records/<int:baby_date_id>',
         views.MiscRecordListView.as_view(), name='misc_records_list'),
    path('baby_date_relate_request/', views.baby_date_relate_request,
         name='baby_date_relate_request'),
    path('approve_baby_date_relate_request/',
         views.approve_baby_date_relate_request,
         name='approve_baby_date_relate_request'),
    path(
        'submit_feeding_with_time/',
        views.submit_feeding_with_time,
        name='submit_feeding_with_time',
    ),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
]

iuser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', views.MyLogoutView.as_view(), name='logout'),
    path('register/', views.user_register, name='register'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('', RedirectView.as_view(url='/dashboard/', permanent=False), name='home'),
    path('0725accounts/', include('iuser.urls')),
    path('zh/admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('shopping_list/', include('shopping_list.urls')),
    path('task_calendar/', include('task_calendar.urls')),
    path('babycare/', include('babycare.urls')),
] + debug_toolbar_urls()

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

from babycare.models import BabyRelation, BabyDate, Feeding, BodyTemperature, GrowthData, Diaper, MiscRecord
from babycare.modelforms import FeedingForm, BodyTemperatureForm, GrowthDataForm, DiaperForm, MiscRecordForm
from task_calendar.models import TaskCalendar
from task_calendar.modelforms import TaskCalendarForm
from shopping_list.models import ShoppingList


def index(request: HttpRequest) -> HttpResponse:
    """
    Render the index page of the dashboard.

    This view handles the request to the dashboard's main page and returns
    the rendered HTML template.
    """
    if request.user.is_anonymous:
        return render(request, 'dashboard/public_index.html')

    context = dict()
    context['active'] = 'index'  # Set the active tab for the navigation bar
    context['task_calendars'] = TaskCalendar.objects.all().order_by('-start_date')
    context['task_form'] = TaskCalendarForm()
    context['shopping_lists'] = ShoppingList.get_recent_lists()
    context['babycare_active'] = request.GET.get(
        'babycare_active', 'baby-feeding')

    if request.session.get_expiry_age() <= 7*24*3600:
        request.session.set_expiry(7 * 24 * 3600)

    baby_dates = BabyRelation.objects.filter(
        request_by=request.user,
        status__in=BabyRelation.accessible_status()
    ).values_list('baby_date', flat=True)
    context['babies'] = babies = []
    for baby_date in BabyDate.objects.filter(id__in=baby_dates):
        baby = dict()
        baby['baby_date'] = baby_date

        baby['feedings'] = Feeding.get_recent_feedings(baby_date.pk)
        baby['feeding_form'] = FeedingForm(initial={'baby_date': baby_date.pk})
            
        baby['body_temperatures'] = BodyTemperature.get_recent_temp(
            baby_date.pk)
        baby['body_temperature_form'] = BodyTemperatureForm(
            initial={'baby_date': baby_date.pk})
        
        baby['growth_data'] = GrowthData.get_recent_growth_data(baby_date.pk)
        baby['growth_data_form'] = GrowthDataForm(
            initial={'baby_date': baby_date.pk})

        baby['diapers'] = Diaper.get_recent_diapers(baby_date.pk)
        baby['diaper_form'] = DiaperForm(
            initial={'baby_date': baby_date.pk}
        )

        baby['misc_records'] = MiscRecord.get_recent_records(baby_date.pk)
        baby['misc_record_form'] = MiscRecordForm(
            initial={'baby_date': baby_date.pk}
        )

        babies.append(baby)
    return render(request, 'dashboard/index.html', context)

dashboard/templates/dashboard/base.html
{% load static %}
{% load theme_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/favicon.ico/favicon-96x96.png" sizes="96x96" />
    <link rel="icon" type="image/svg+xml" href="/favicon.ico/favicon.svg" />
    <link rel="shortcut icon" href="/favicon.ico/favicon.ico" />
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon.ico/apple-touch-icon.png" />
    <link rel="manifest" href="/favicon.ico/site.webmanifest" />
    <title>{% block title %}{% endblock %}</title>
    {% block style_links %}
    {% endblock %}
    <style>
        @font-face {
            font-display: block;
            font-family: "bootstrap-icons";
            src: url("{% static 'font/bootstrap-icons.woff2' %}") format("woff2"),
            url("{% static 'font/bootstrap-icons.woff' %}") format("woff");
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/switcher.css' %}">
    <link rel="stylesheet" href="{% static 'css/task_calendar/task_calendar.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/babycare/babycare.css' %}">
    <link rel="stylesheet" href="{% static 'css/shopping_list/shopping_list.css' %}">
</head>

<body>
    {% block navbar %}
    <nav class="navbar bg-body shadow-sm navbar-expand-sm fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'dashboard:index' %}">Familee</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">导航</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-startflex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link {% if active == 'index' %}active{% endif %}" href="{% url 'dashboard:index' %}">首页</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if active == 'babycare' %}active{% endif %}" href="{% url 'babycare:index' %}">成长记录</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if active == 'list' %}active{% endif %}" href="#">清单</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if active == 'task' %}active{% endif %}" href="#">计划</a>
                        </li>
                        {{ request|theme }}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username|default:"用户" }}
                            </a>
                            <ul class="dropdown-menu">
                                {% if request.user.is_superuser %}
                                <li class="nav-item dropdown-item">
                                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                                </li>
                                {% endif %}
                                <li class="nav-item dropdown-item"><form action="{% url 'logout' %}" method="post">{% csrf_token %}<input class="nav-link unobvious-button" type="submit" value="退出登录"></form></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    {% endblock %}
    <div id="main-container" class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <main>
                    {% block messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endblock %}
                    {% block main %}
                    {% endblock %}
                </main>
            </div>
            <div class="col-lg-4 col-md-12">
                <aside>
                    {% block aside %}
                    <section id="task-calendar">
                        <h3>近期计划</h3>
                        <div>
                            <div><button type="button" id="create-task-calendar" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#create-task-calendar-modal">+ 添加计划</button></div>
                            {% if task_calendars %}
                                {% include "task_calendar/includes/task_list_simple.html" %}
                            {% else %}
                                <div class="lead">暂无计划</div>
                            {% endif %}
                            <div class="modal fade" tabindex="-1" id="create-task-calendar-modal">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">新增计划</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{% url 'create_task' %}" method="post">
                                            {{ task_form.as_p }}
                                            {% csrf_token %}
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                                        <button id="task-calendar-create-submit" type="button" class="btn btn-primary">确认</button>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <section id="shopping-list">
                        <h3>清单</h3>
                        <ul id="shopping-lists">
                            {% for list in shopping_lists %}
                            <li class="shopping-list"><a href="{% url 'shopping_list_detail' list.id %}">
                                <div>
                                    <div>{{list.name}}</div>
                                    <div><small>共 {{ list.categories.count }} 品类 有 {{ list.get_item_count }} 单品</small></div>
                                </div>
                            </a></li>
                            {% empty %}
                            <li>清单为空</li>
                            {% endfor %}
                        </ul>
                    </section>
                    {% endblock %}
                </aside>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/d3.v7.min.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <script src="{% static 'js/switcher.js' %}"></script>
    <script src="{% static 'js/auto_submit.js' %}"></script>
    <script src="{% static 'js/task_calendar/task_calendar.js' %}"></script>
    <script src="{% static 'js/babycare/babycare_curve.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

dashboard/templates/dashboard/index.html
{% extends "dashboard/base.html" %}

{% block title %}主页{% endblock %}

{% block main %}
{% if babies %}
<div class="switcher">
    <div class="switcher-buttons">
        {% for baby in babies %}
        <div class="switcher-button{% if forloop.first %} active-button{% endif %}" data-target="baby{{ baby.baby_date.id }}">{{ baby.baby_date.nickname }}</div>
        {% empty %}
        {% endfor %}
    </div>
    <div class="switcher-contents">
        {% for baby in babies %}
        <div class="switcher-content block-switcher{% if forloop.first %} active-content{% endif %}" id="baby{{ baby.baby_date.id }}">
            <section>
                {% include "babycare/includes/babydate.html" with baby_date=baby.baby_date %}
            </section>
            <section>
                <h2>成长记录</h2>
                {% include "babycare/includes/baby_record.html" with baby_date=baby.baby_date feedings=baby.feedings feeding_form=baby.feeding_form body_temperatures=baby.body_temperatures body_temperature_form=baby.body_temperature_form growth_data=baby.growth_data growth_data_form=baby.growth_data_form diapers=baby.diapers diaper_form=baby.diaper_form misc_records=baby.misc_records misc_record_form=baby.misc_record_form %}
            </section>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    {% include 'babycare/includes/baby_create_or_link.html' %}
{% endif %}
{% endblock %}

dashboard/templates/dashboard/public_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>首页</title>
</head>
<body>
    <h1>工作笔记</h1>
    <h2>程序员代码工作笔记文档简介</h2>

    <p>
        代码工作笔记是程序员日常开发中不可或缺的高效工具，用于记录技术要点、项目思路、解决方案及踩坑经验。这份文档旨在帮助开发者系统化整理代码逻辑、算法实现、API调用、调试过程等关键信息，提升开发效率与代码可维护性。  
    </p>
<p>
    内容可包括:
    <ol>
        <li><b>代码片段</b>：常用模板、核心函数或优化后的代码； </li>
        <li><b>问题日志</b>：记录Bug成因与解决步骤，便于复盘；  </li>
        <li><b>技术备忘</b>：框架配置、命令行操作、数据库查询技巧等；  </li>
        <li><b>项目规划</b>：模块设计、需求变更及进度跟踪。 </li>
    </ol>
</p>

<p>
    通过清晰的分类（如Markdown标签或代码注释），笔记既能作为个人知识库，也能为团队协作提供参考。定期回顾可加速技术成长，减少重复性工作。  
</p>

<p>—— 用文档沉淀思考，让代码有迹可循。</p>
<footer>
    <span>
        <img src="{% get_media_prefix %}images/备案编号图标.png" alt="备案">
        <a href="https://beian.mps.gov.cn/#/query/webSearch?code=34030002001297" rel="noreferrer" target="_blank">皖公网安备34030002001297号</a>
    </span>
    <a href="https://beian.miit.gov.cn">皖ICP备2025090538号-1</a>
</footer>
</body>
</html>